---
id: labguide
name: Azure Experience Center Management Portal for CheckPoint Sandblast

content:
  url: https://raw.githubusercontent.com/Suraj2093/Azure-Experience-Centre/master/docs

vars:
  USER_NAME: "(email)"
  USER_PASSWORD: "(email)"
  GIT_HOST: github
  DOCS_URL: docs.spektrasystems.com


modules:
  activate:
  - GettingStarted
  - CreateAECTemplate
  - validateTemplate
  - CreatingAndManagingODL
  - ODLUsermanagement
  - checklist
